// src/components/Molecules/Socials/Socials.svelte
<script>
</script>

<div class="socials piko-t-meta piko-card piko-prose__block">
	<dl class="list">
		<dt>Mastodon:</dt>
		<dd>
			<a
				href="https://mastodonapp.uk/@djmarland"
				target="_blank"
				rel="noopener noreferrer">@djmarland@mastodonapp.uk</a
			>
		</dd>
		<dt>Bluesky:</dt>
		<dd>
			<a
				href="https://bsky.app/profile/djmarland.bsky.social"
				target="_blank"
				rel="noopener noreferrer">@djmarland.bsky.social</a
			>
		</dd>
	</dl>
</div>

<style>
	.socials {
		container-type: inline-size;
	}

	@container (max-width: 400px) {
		.list {
			grid-template-columns: 1fr;
		}
	}
</style>

// src/components/Molecules/Socials/Socials.tsx
import { cx } from "@/components/cx";
import styles from "./Socials.module.css";

export default function Socials() {
	return (
		<div
			className={cx(
				styles.socials,
				"piko-t-meta",
				"piko-card",
				"piko-prose__block",
			)}
		>
			<dl className={styles.list}>
				<dt>Mastodon:</dt>
				<dd>
					<a
						href="https://mastodonapp.uk/@djmarland"
						target="_blank"
						rel="noopener noreferrer"
					>
						@djmarland@mastodonapp.uk
					</a>
				</dd>
				<dt>Bluesky:</dt>
				<dd>
					<a
						href="https://bsky.app/profile/djmarland.bsky.social"
						target="_blank"
						rel="noopener noreferrer"
					>
						@djmarland.bsky.social
					</a>
				</dd>
			</dl>
		</div>
	);
}
