// src/routes/(admin)/admin/posts/+page.svelte
<script lang="ts">
    import {resolve} from "$app/paths";
    import PaginationNav from "@/components/PaginationNav.svelte";
    import type {PageData} from "./$types";
    import {isPostPublic} from "$lib/blog";

    interface Props {
		data: PageData;
	}

	let { data }: Props = $props();

	let query = $state("");

	$effect(() => {
		query = data.filters?.query ?? "";
	});

	function buildHref(page: number) {
		const params = new URLSearchParams();
		if (query) params.set("query", query);
		params.set("page", String(page));
		return `/admin/posts?${params.toString()}`;
	}
</script>

<svelte:head>
	<title>Manage Posts</title>
</svelte:head>

<div class="piko-page-container piko-vstack">
	<h1 class="piko-t-h1">Manage Posts</h1>

	<form method="get" class="filters-form">
		<label class="piko-hidden" for="query">Search</label>
		<div class="piko-hstack">
			<input
				id="query"
				type="text"
				name="query"
				placeholder="Search posts..."
				value={query}
				onchange={(e) => (query = e.currentTarget.value)}
			/>
			<button type="submit">Search</button>
		</div>
	</form>

	<hr />

	<p>
		Showing {data.posts.length} of {data.totalCount} posts
		{#if query}
			matching "{query}"
		{/if}
	</p>

	{#if data.posts.length === 0}
		<p>
			No posts found. {#if query}Try adjusting your search.{/if}
		</p>
	{:else}
		<table>
			<thead>
				<tr>
					<th>Title</th>
					<th>Slug</th>
					<th>Status</th>
					<th>Publication Datetime</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{#each data.posts as post (post.id)}
					<tr
						class="status-row"
						data-state={post.publishedAt
							? isPostPublic(post.publishedAt)
								? "success"
								: "warning"
							: "error"}
					>
						<td>
							<a href={resolve(`/admin/posts/${post.id}/edit`)}>{post.title}</a>
						</td>
						<td class="slug-cell">{post.slug}</td>
						<td>
							{post.publishedAt
								? isPostPublic(post.publishedAt)
									? "Published"
									: "Scheduled"
								: "Draft"}
						</td>
						<td>
							{post.publishedAt
								? new Date(post.publishedAt).toLocaleDateString("en-US", {
										year: "numeric",
										month: "short",
										day: "numeric",
										hour: "2-digit",
										minute: "2-digit",
										hour12: false,
									})
								: "-"}
						</td>
						<td>
							<a href={resolve(`/posts/${post.slug}`)}
								>{post.publishedAt ? "View" : "Preview"}</a
							>
							{#if !post.publishedAt}
								<a href={resolve(`/admin/posts/${post.id}/publish`)}
									>Publish</a
								>
							{/if}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>

		<PaginationNav
			page={data.page}
			totalPages={data.totalPages}
			buildHref={(p) => buildHref(p)}
		/>
	{/if}
</div>

<style>
	.slug-cell {
		color: var(--piko-color-text-subtle);
		font-family: monospace;
	}
	.status-row {
		background-color: var(--piko-color-state-background);
	}
</style>

// src/app/admin/posts/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getAdminSessionUser } from "@/lib/admin-auth";
import { getAllPostsForAdmin } from "@/lib/posts";
import { isPostPublic } from "@/lib/blog";
import PaginationNav from "@/components/PaginationNav";
import styles from "./page.module.css";

export const metadata: Metadata = {
	title: "Manage Posts",
};

interface AdminPostsPageProps {
	searchParams: Promise<{ query?: string; page?: string }>;
}

export default async function AdminPostsPage({
	searchParams,
}: AdminPostsPageProps) {
	const session = await getAdminSessionUser();
	if (!session) {
		redirect("/admin/login");
	}

	const { query = "", page = "1" } = await searchParams;
	const result = await getAllPostsForAdmin({ query, page });

	function buildHref(targetPage: number) {
		const params = new URLSearchParams();
		if (result.filters.query) {
			params.set("query", result.filters.query);
		}
		params.set("page", String(targetPage));
		return `/admin/posts?${params.toString()}`;
	}

	return (
		<div className="piko-page-container piko-vstack">
			<h1 className="piko-t-h1">Manage Posts</h1>

			<form method="GET" className="piko-hstack">
				<label className="piko-hidden" htmlFor="query">
					Search
				</label>
				<input
					id="query"
					type="text"
					name="query"
					placeholder="Search posts..."
					defaultValue={result.filters.query}
				/>
				<button type="submit">Search</button>
			</form>

			<hr />

			<p>
				Showing {result.posts.length} of {result.totalCount} posts
				{result.filters.query ? ` matching "${result.filters.query}"` : ""}
			</p>

			{result.posts.length === 0 ? (
				<p>
					No posts found.{" "}
					{result.filters.query ? "Try adjusting your search." : ""}
				</p>
			) : (
				<>
					<table>
						<thead>
							<tr>
								<th>Title</th>
								<th>Slug</th>
								<th>Status</th>
								<th>Publication Datetime</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							{result.posts.map((post) => {
								const state = post.publishedAt
									? isPostPublic(post.publishedAt)
										? "success"
										: "warning"
									: "error";
								const statusLabel = post.publishedAt
									? isPostPublic(post.publishedAt)
										? "Published"
										: "Scheduled"
									: "Draft";

								return (
									<tr
										key={post.id}
										className={styles.statusRow}
										data-state={state}
									>
										<td>
											<Link href={`/admin/posts/${post.id}/edit`}>
												{post.title}
											</Link>
										</td>
										<td className={styles.slugCell}>{post.slug}</td>
										<td>{statusLabel}</td>
										<td>
											{post.publishedAt
												? new Date(post.publishedAt).toLocaleDateString(
														"en-US",
														{
															year: "numeric",
															month: "short",
															day: "numeric",
															hour: "2-digit",
															minute: "2-digit",
															hour12: false,
														},
													)
												: "-"}
										</td>
										<td>
											<Link href={`/posts/${post.slug}`}>
												{post.publishedAt ? "View" : "Preview"}
											</Link>
											{!post.publishedAt && (
												<>
													{" "}
													<Link href={`/admin/posts/${post.id}/publish`}>
														Publish
													</Link>
												</>
											)}
										</td>
									</tr>
								);
							})}
						</tbody>
					</table>

					<PaginationNav
						page={result.page}
						totalPages={result.totalPages}
						buildHref={buildHref}
					/>
				</>
			)}
		</div>
	);
}
