// src/routes/(site)/tags/[slug]/+page.svelte
<script lang="ts">
	import { resolve } from "$app/paths";
	import type { PageData } from "./$types";
	import PostCard from "@/components/Blog/PostCard.svelte";
	import PaginationNav from "@/components/PaginationNav.svelte";

	type Props = { data: PageData };
	let { data }: Props = $props();
	const archive = $derived(data.archive);

	function buildTagHref(slug: string, page: number) {
		return page > 1 ? `/tags/${slug}?page=${page}` : `/tags/${slug}`;
	}
</script>

<svelte:head>
	<title>#{archive.tag.name} | Hammerspace</title>
	<meta name="description" content={`Posts tagged ${archive.tag.name}`} />
	<link
		rel="canonical"
		href="https://www.hammerspace.co.uk/tags/{archive.tag.slug}"
	/>
</svelte:head>

<main class="container">
	<header class="header">
		<div class="tagTitle">
			<h1>#{archive.tag.name}</h1>
			<a href={resolve("/posts")} class="actionLink"> Back to archive </a>
		</div>
		<p class="intro">
			{archive.posts.totalCount === 0
				? "No public posts currently use this tag."
				: `${archive.posts.totalCount} post${archive.posts.totalCount === 1 ? "" : "s"} currently visible under this tag.`}
		</p>
	</header>
	<div class="list">
		{#each archive.posts.posts as post (post.id)}
			<PostCard {post} />
		{/each}
	</div>
	<PaginationNav
		page={archive.posts.page}
		totalPages={archive.posts.totalPages}
		buildHref={(nextPage) => buildTagHref(archive.tag.slug, nextPage)}
	/>
</main>

<style>
	.container {
		max-width: 960px;
		margin: 0 auto;
		padding: 2rem 0 3rem;
	}

	.header {
		display: grid;
		gap: 1rem;
		margin-bottom: 2rem;
	}

	.header h1 {
		margin: 0;
		font-size: clamp(2rem, 1.7rem + 1vw, 3rem);
	}

	.intro {
		margin: 0;
		color: color-mix(in srgb, currentColor 75%, transparent);
	}

	.actionLink {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		padding: 0.7rem 1rem;
		border: 1px solid color-mix(in srgb, currentColor 18%, transparent);
		border-radius: 999px;
		text-decoration: none;
		background: transparent;
		font: inherit;
		cursor: pointer;
	}

	.tagTitle {
		display: flex;
		flex-wrap: wrap;
		align-items: baseline;
		gap: 0.5rem;
	}

	.list {
		display: grid;
		gap: 1rem;
	}
</style>

// src/app/tags/[slug]/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPublicTagArchive } from "@/actions/posts";
import PostCard from "@/components/Blog/PostCard";
import pageStyles from "@/components/Blog/BlogPage.module.css";
import PaginationNav from "@/components/PaginationNav";
import { absoluteUrl } from "@/lib/site";

export const revalidate = 60;

interface TagArchivePageProps {
	params: Promise<{ slug: string }>;
	searchParams: Promise<{ page?: string }>;
}

function buildTagHref(slug: string, page: number) {
	return page > 1 ? `/tags/${slug}?page=${page}` : `/tags/${slug}`;
}

export default async function TagArchivePage({ params, searchParams }: TagArchivePageProps) {
	const [{ slug }, { page }] = await Promise.all([params, searchParams]);
	const archive = await getPublicTagArchive({ slug, page });
	if (!archive) {
		notFound();
	}

	return (
		<main className={pageStyles.container}>
			<header className={pageStyles.header}>
				<div className={pageStyles.tagTitle}>
					<h1>#{archive.tag.name}</h1>
					<Link href="/blog" className={pageStyles.actionLink}>
						Back to archive
					</Link>
				</div>
				<p className={pageStyles.intro}>
					{archive.posts.totalCount === 0
						? "No public posts currently use this tag."
						: `${archive.posts.totalCount} post${archive.posts.totalCount === 1 ? "" : "s"} currently visible under this tag.`}
				</p>
			</header>
			<div className={pageStyles.list}>
				{archive.posts.posts.map((post) => (
					<PostCard key={post.id} post={post} />
				))}
			</div>
			<PaginationNav
				page={archive.posts.page}
				totalPages={archive.posts.totalPages}
				buildHref={(nextPage) => buildTagHref(archive.tag.slug, nextPage)}
			/>
		</main>
	);
}

export async function generateMetadata({ params }: TagArchivePageProps): Promise<Metadata> {
	const { slug } = await params;
	const archive = await getPublicTagArchive({ slug, page: 1 });
	if (!archive) {
		return {};
	}

	return {
		title: `#${archive.tag.name}`,
		description: `Posts tagged ${archive.tag.name}`,
		alternates: { canonical: absoluteUrl(`/tags/${archive.tag.slug}`) },
	};
}
