// src/app/admin/page.tsx
import Link from "next/link";
import { redirect } from "next/navigation";
import PasskeySetup from "@/components/PasskeySetup";
import LogoutButton from "@/components/Organisms/LogoutButton/LogoutButton.tsx";
import { getAdminSessionUser } from "@/lib/admin-auth";
import styles from "./page.module.css";

interface AdminDashboardProps {
	searchParams?: Promise<Record<string, string | string[] | undefined>>;
}

export default async function AdminDashboard({
	searchParams,
}: AdminDashboardProps) {
	const session = await getAdminSessionUser();
	if (!session) {
		redirect("/admin/login");
	}

	const resolvedSearchParams = searchParams ? await searchParams : {};
	const shouldHighlightSetup = resolvedSearchParams.setupPasskey === "1";

	return (
		<div className={styles.container}>
			<header className={styles.header}>
				<h1>Admin Dashboard</h1>
				<p>Welcome, {session.name || "Admin"}</p>
			</header>

			{shouldHighlightSetup && !session.hasPasskey && (
				<p>
					Please add your passkey now. Your login token will be invalidated
					after setup.
				</p>
			)}

			<PasskeySetup hasPasskey={session.hasPasskey} />

			<nav className={styles.nav}>
				<Link href="/admin/posts" className={styles.button}>
					Manage Posts
				</Link>
				<Link href="/admin/posts/new" className={styles.button}>
					New Post
				</Link>
				<Link href="/admin/tags" className={styles.button}>
					Manage Tags
				</Link>
				<LogoutButton />
			</nav>

			<section className={styles.content}>
				<p>Manage drafts, publish posts, and edit existing content.</p>
			</section>
		</div>
	);
}

// src/routes/admin/+page.svelte
<script lang="ts">
	import PasskeySetup from '@/components/PasskeySetup.svelte';
	import LogoutButton from '@/components/Organisms/LogoutButton/LogoutButton.svelte';
	import styles from './page.module.css';
	import type { PageData } from './$types';

	export let data: PageData;

	let session = data.session;
	let setupPasskey = data.setupPasskey;

	$: ({ session, setupPasskey } = data);
</script>

<svelte:head>
	<title>Admin Dashboard</title>
</svelte:head>

<div class={styles.container}>
	<header class={styles.header}>
		<h1>Admin Dashboard</h1>
		<p>Welcome, {session.name || 'Admin'}</p>
	</header>

	{#if setupPasskey && !session.hasPasskey}
		<p>
			Please add your passkey now. Your login token will be invalidated after
			setup.
		</p>
	{/if}

	<PasskeySetup hasPasskey={session.hasPasskey} />

	<nav class={styles.nav}>
		<a href="/admin/posts" class={styles.button}>Manage Posts</a>
		<a href="/admin/posts/new" class={styles.button}>New Post</a>
		<a href="/admin/tags" class={styles.button}>Manage Tags</a>
		<LogoutButton />
	</nav>

	<section class={styles.content}>
		<p>Manage drafts, publish posts, and edit existing content.</p>
	</section>
</div>
