// src/components/Admin/ConfirmSubmitButton.tsx
"use client";

import { useFormStatus } from "react-dom";
import type { MouseEvent } from "react";

interface ConfirmSubmitButtonProps {
	label: string;
	confirmMessage: string;
	className?: string;
}

export default function ConfirmSubmitButton({
	label,
	confirmMessage,
	className,
}: ConfirmSubmitButtonProps) {
	const { pending } = useFormStatus();

	function handleClick(event: MouseEvent<HTMLButtonElement>) {
		if (pending) {
			return;
		}
		if (!window.confirm(confirmMessage)) {
			event.preventDefault();
		}
	}

	return (
		<button
			type="submit"
			className={className}
			disabled={pending}
			onClick={handleClick}
		>
			{pending ? "Working..." : label}
		</button>
	);
}

// src/components/Admin/ConfirmSubmitButton.svelte
<script lang="ts">
	interface Props {
		label: string;
		confirmMessage: string;
		className?: string;
	}

	const { label, confirmMessage, className }: Props = $props();

	let pending = $state(false);

	function handleClick(event: MouseEvent) {
		if (pending) {
			return;
		}
		if (!window.confirm(confirmMessage)) {
			event.preventDefault();
		}
	}
</script>

<button
	type="submit"
	class={className}
	disabled={pending}
	onclick={handleClick}
>
	{pending ? "Working..." : label}
</button>
