// src/app/admin/page.tsx
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Link from "next/link";
import { getAdminSessionUser } from "@/lib/admin-auth";
import LogoutButton from "@/components/Organisms/LogoutButton/LogoutButton";
import PasskeySetup from "@/components/PasskeySetup";
import { cx } from "@/components/cx";
import styles from "./page.module.css";

export const metadata: Metadata = {
	title: "Admin Dashboard",
};

interface AdminDashboardPageProps {
	searchParams: Promise<{ setupPasskey?: string }>;
}

export default async function AdminDashboardPage({
	searchParams,
}: AdminDashboardPageProps) {
	const session = await getAdminSessionUser();
	if (!session) {
		redirect("/admin/login");
	}

	const { setupPasskey: setupPasskeyParam } = await searchParams;
	const setupPasskey = setupPasskeyParam === "1";

	return (
		<div className="piko-page-container piko-vstack">
			<header className={cx(styles.header, "piko-vstack--small")}>
				<h1 className="piko-t-h1">Admin Dashboard</h1>
				<p>Welcome, {session.name || "Admin"}</p>
			</header>

			{setupPasskey && !session.hasPasskey && (
				<p data-state="info" className="piko-state__box">
					Please add your passkey now. Your login token will be invalidated
					after setup.
				</p>
			)}

			<PasskeySetup hasPasskey={session.hasPasskey} />

			<nav className={cx(styles.nav, "piko-hstack")}>
				<Link href="/admin/posts" className="piko-button">
					Manage Posts
				</Link>
				<Link href="/admin/posts/new" className="piko-button">
					New Post
				</Link>
				<Link href="/admin/tags" className="piko-button">
					Manage Tags
				</Link>
				<LogoutButton />
			</nav>

			<section>
				<p>Manage drafts, publish posts, and edit existing content.</p>
			</section>
		</div>
	);
}

// src/routes/(admin)/admin/+page.svelte
<script lang="ts">
	import { resolve } from "$app/paths";
	import PasskeySetup from "@/components/PasskeySetup.svelte";
	import LogoutButton from "@/components/Organisms/LogoutButton/LogoutButton.svelte";
	import type { PageData } from "./$types";

	type Props = { data: PageData };
	let { data }: Props = $props();
	const session = $derived(data.session);
	const setupPasskey = $derived(data.setupPasskey);
</script>

<svelte:head>
	<title>Admin Dashboard</title>
</svelte:head>

<div class="container">
	<header class="header">
		<h1>Admin Dashboard</h1>
		<p>Welcome, {session.name || "Admin"}</p>
	</header>

	{#if setupPasskey && !session.hasPasskey}
		<p>
			Please add your passkey now. Your login token will be invalidated after
			setup.
		</p>
	{/if}

	<PasskeySetup hasPasskey={session.hasPasskey} />

	<nav class="nav">
		<a href={resolve("/admin/posts")} class="button">Manage Posts</a>
		<a href={resolve("/admin/posts/new")} class="button">New Post</a>
		<a href={resolve("/admin/tags")} class="button">Manage Tags</a>
		<LogoutButton />
	</nav>

	<section class="content">
		<p>Manage drafts, publish posts, and edit existing content.</p>
	</section>
</div>

<style>
	.container {
		max-width: var(--piko-page-max);
		margin: 0 auto;
		padding: var(--piko-space-5);
	}

	.header {
		text-align: center;
		margin-bottom: var(--piko-space-7);
		padding: var(--piko-space-7) var(--piko-space-5);
		border-bottom: 1px solid var(--piko-color-border);
	}

	.header h1 {
		font-size: 2.5rem;
		margin-bottom: var(--piko-space-2);
	}

	.header p {
		font-size: 1rem;
		color: var(--piko-color-text-subtle);
	}

	.nav {
		display: flex;
		gap: var(--piko-space-2);
		margin-bottom: var(--piko-space-7);
		padding: var(--piko-space-5) 0;
	}

	.button {
		padding: var(--piko-space-control-padding-y)
			var(--piko-space-control-padding-x);
		border: 1px solid var(--piko-color-primary-border);
		border-radius: 0;
		background-color: var(--piko-color-primary-bg);
		color: var(--piko-color-primary-text);
		text-decoration: none;
		cursor: pointer;
		font-size: 1rem;
		transition: all 0.2s ease;
	}

	.button:hover {
		background-color: var(--piko-color-primary-border);
		border-color: var(--piko-color-primary-border);
	}

	.content {
		margin-top: var(--piko-space-7);
	}
</style>
