// src/components/Blog/MarkdownContent.tsx
import { renderMarkdown } from "@/lib/markdown";
import { cx } from "@/components/cx";
import styles from "./MarkdownContent.module.css";

interface MarkdownContentProps {
	content: string;
}

export default function MarkdownContent({ content }: MarkdownContentProps) {
	let html: string;
	try {
		html = renderMarkdown(content);
	} catch (error) {
		console.error("Markdown rendering error:", error);
		html = `<p>${content}</p>`;
	}

	return (
		<div
			className={cx("piko-prose__block", styles.markdownContent)}
			// Content is admin-authored and trusted directly.
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
}

// src/components/Blog/MarkdownContent.svelte
<script lang="ts">
    import {renderMarkdown} from "@/lib/markdown";
    import {onMount, tick} from "svelte";
    import {highlightAll} from "microlighter";

    interface Props {
        content: string;
    }

    const {content}: Props = $props();

    const html = $derived.by(() => {
        try {
            return renderMarkdown(content);
        } catch (e) {
            console.error("Markdown rendering error:", e);
            return `<p>${content}</p>`;
        }
    });

    onMount(async () => {
        await tick();
        await highlightAll();
    });
</script>

<div class="piko-prose__block">{@html html}</div>
