// src/components/Blog/PostBody.svelte
<script lang="ts">
	import type { PublicPostSummary } from "@/lib/posts";
	import MarkdownContent from "@/components/Blog/MarkdownContent.svelte";
	import ReadingTime from "@/components/Blog/ReadingTime.svelte";
	import Socials from "@/components/Molecules/Socials/Socials.svelte";

	type Props = {
		post: Pick<
			PublicPostSummary,
			"content" | "coverImageUrl" | "coverImageAlt" | "wordCount"
		>;
	};

	let { post }: Props = $props();
</script>

<div class="body">
	{#if post.coverImageUrl}
		<img
			src={post.coverImageUrl}
			alt={post.coverImageAlt || ""}
			class="image"
		/>
	{/if}
	<div class="markdown piko-prose">
		<MarkdownContent content={post.content} />
		<Socials />
	</div>
	<ReadingTime wordCount={post.wordCount} variant="footer" />
</div>

<style>
	.body {
		display: grid;
		gap: 1.25rem;
	}

	.image {
		width: 100%;
		height: auto;
	}
</style>

// src/components/Blog/PostBody.tsx
import type { PublicPostSummary } from "@/lib/posts";
import MarkdownContent from "@/components/Blog/MarkdownContent";
import ReadingTime from "@/components/Blog/ReadingTime";
import Socials from "@/components/Molecules/Socials/Socials";
import styles from "./PostBody.module.css";

// "markdown" is a bare hook class with no matching CSS rule; "piko-prose"
// carries the actual prose styling.

interface PostBodyProps {
	post: Pick<
		PublicPostSummary,
		"content" | "coverImageUrl" | "coverImageAlt" | "wordCount"
	>;
}

export default function PostBody({ post }: PostBodyProps) {
	return (
		<div className={styles.body}>
			{post.coverImageUrl && (
				<img
					src={post.coverImageUrl}
					alt={post.coverImageAlt || ""}
					className={styles.image}
				/>
			)}
			<div className="markdown piko-prose">
				<MarkdownContent content={post.content} />
				<Socials />
			</div>
			<ReadingTime wordCount={post.wordCount} variant="footer" />
		</div>
	);
}
